### ISSUE TITLE
Broken dependency in Python 3.10

### ISSUE THREAD

**Issue by aaronchantrill** [CITGuru/PyInquirer#172]
PyInquirer requires prompt-toolkit 1.0.14 which imports Mapping from collections in styles/from_dict.py. For python 3.10, this needs to be updated to `from collections.abc import Mapping`. The current version of prompt-toolkit appears to be 3.0.24, so it seems likely that updating this library would fix the issue.

**Comment by aaronchantrill** [comment]
Sorry, redirected here by PyPi. I see that this current version requires prompt-toolkit 3..3.1 since July 2020. Apologies.

**Comment by Cellebyte** [comment]
@aaronchantrill you are right, but it should be updated on pypi. The current version enforces an older prompt_toolkit version which does not work with python 3.10.
```
prompt_toolkit==1.0.14
Pygments>=2.2.0
regex>=2016.11.21
```
this together with python 3.10 is breaking the compatibility.
Because poetry would not install the version 3.x.y of prompt_toolkit.
PyInquirer should release a new version which uses a newer prompt_toolkit.

**Comment by S4nd3sh** [comment]
The PyPi install still enforces the install of prompt_toolkit==1.0.14 as of today(Jul-2023).  

Also, as mentioned above running this on 3.10.x is a nightmare. 
Don't think this is a closed issue yet.
